### ISSUE TITLE
Use cert manager for certificate management instead of our own embedded golang code (jumpstarter-controller)

### ISSUE THREAD

**Issue by mangelajo** [jumpstarter-dev/jumpstarter#103]
With cert-manager we can get our keys/certificates and a CA like this:

PLEASE NOTE: Expiration/renewal times need to be addressed

An issuer to create our initial CA key pair
```
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app: jumpstarter
  name: jumpstarter-self-signed
  namespace: jumpstarter-lab
spec:
  selfSigned: {}
```

a key for the CA:
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: jumpstarter
  name: jumpstarter-selfsigned
  namespace: jumpstarter-lab
spec:
  commonName: jumpstarter-selfsigned-ca
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: jumpstarter-self-signed
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: ca.crt
```

our CA (Issuer):
```
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app: jumpstarter
  name: jumpstarter
  namespace: jumpstarter-lab
spec:
  ca:
    secretName: ca.crt
```

the Certificate for the service (by using our CA, or ... just any other issuer on the system)
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: jumpstarter
  name: jumpstarter-tls
  namespace: jumpstarter-lab
spec:
  commonName: jumpstarter
  dnsNames:
  - grpc.demo.jumpstarter.dev
  - router.demo.jumpstarter.dev
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: jumpstarter
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  secretName: jumpstarter-tls
  subject:
    organizations:
    - Jumpstarter server
  usages:
  - server auth
  - digital signature
  - key encipherment
  - key agreement
  - data encipherment
```
