### ISSUE TITLE
When using an OVH kubeconfig the admin interface fails with SSL issues on MacOS

### ISSUE THREAD

**Issue by mangelajo** [jumpstarter-dev/jumpstarter#362]
KUBECONFIG=config-ovh-red

jmp admin create exporter -n jumpstarter-lab -l board pico-rp2350  pico-rp2350-1 --out pico-rp2350-1.yaml

will result in:
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host rwc7lj.c1.uk1.k8s.ovh.net:443 ssl:True [SSLCertVerificationError: ('“kube-apiserver” certificate is not standards compliant',)]

possibly related to:

https://github.com/golang/go/issues/51991

interestingly, the direct usage of kubernetes and kubernetes_asyncio seem to be fine... 

example kubeconfig with no user token: 
```

cat ~/.kube/config-ovh-red
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZCRENDQXV5Z0F3SUJBZ0lCS2pBTkJna3Foa2lHOXcwQkFRc0ZBREFSTVE4d0RRWURWUVFEREFaeWQyTTMKYkdvd0hoY05NalV3TXpFNE1EZzFOVFUxV2hjTk5EQXdNekUwTURnMU5UVTFXakFSTVE4d0RRWURWUVFEREFaeQpkMk0zYkdvd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUURCbmhweSt5SjVlWjNsCnlrQjlJd21vVU9NV0x6Q3VVZjdTU1VLSlJmR0xYZjlZbEFYUFZKZnY0ZWY5R0xQREZpenhLek56K2IzZFlXUVAKNXJ3UmtiQk95OTJNVU0vQ0NsOEQ4K0xQa0Exb1lRVENobTZ2TERKdXFvZFFXMmRTSEZDaHNvZEVTSkNnRnE4cApzcUlGN3FTSEpJUm1SY3IyNFdYOHhaQm1mYUJpbmNva0JsUElXcjVDaWhZNWlRZGN4TnJuUGEreTFRNGFTMStyClBid21lQ3c2VmxrQmZMQkhNc2wzVnNia3dhb25TN201a2VmcllVc0JCVnV6WThSalZFWTgvTjl1T282US9MS0YKeEZRSWM1cXJPN3pLRjBLNERjdnZKL3ZtL2hHV0VoMXZKT1JKa0RLT0oxMEFkMjFqMVovUllGSHZOOTNrUCtPSQpqT3NRU3NSSFZjY3RDVmg4RGg0LzRhTE5lQ3ZZQmVubkRzWEZMRDYyY001bGpjNklCRU5ESHFJQ0JRd2NvcG1mCmh3TXFlQzFSd3dLYkY1clR6alQ2eUN4SHJ4UFcwK1ZjWGJjbnpBcHUxT2VSRlI3eXpyR0Q1SnNWNkRxSTZERVAKUjRibmVMblVTaDRPdjN3UnhOYlFwNVpJSjNiRFhYRXVKMnd4M3NCTXBBOWRrc3dMeXFYbGxKdWxndElmU2VKWgprOHNFdlNsSEZEbExuUnNuQ3JFVEZrK2FpUFkyZVVDRDVLeHlVeEtDNVBNTzc3WkFHelpxcVg5dlRYd2Y1bG9wCi95MkxTZlV5d1lMMjJPeUhPNFp2Z2Npdi83S1VVdHVEdXVubmRPZnpQM0U1cE9UQzBCclB6LzRBWjIrZTE4SGkKMVpweFp4NzZqaFc5MFNGTEcrS3R2UjNTTHFnNXN3SURBUUFCbzJjd1pUQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQTRHQTFVZER3RUIvd1FFQXdJQkJqQWRCZ05WSFE0RUZnUVV4NmxIanljN09NK3diWVZud0VxaTdjRUp4aGN3Ckl3WURWUjBqQkJ3d0dxRVZwQk13RVRFUE1BMEdBMVVFQXd3R2NuZGpOMnhxZ2dFcU1BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUNBUUNUaDFqODR0K2lWUmhvRjJ1Vi9VQUo2amVFNkEyZWpMMzV0dFByMDc5d1hRL1A4WGdYUnFoUgovUDRFQlQwVkhyWkZ0bTRDaW0rNXBlWmgwUGZpYWtJVU5yY21oTlhRZ3dITFI2d3k1K0JRYjFuMTUzRFpyM0RDCnhRTVR0UVBzUmpqSEY0UXpucjZHSy9DTFlDRjQxRXJVaXAwaS9JL3o5T3E2KzJDOHVCQ2tTcFVPYzRhTnMvOC8KV1pKY0ltU1NwUm1tOWI4UnhvUzg1RE1LNnoxcFZOaUtYaU9nVjRQV205UnZNSndjVTJlK3BXMENhY2FQR2FVSQpSQllLYi9rVmZzaGhxaUtGNlF5SlVCVDJHZ1ZDdlNheFk1WWgxY2FndVlDVEk4NG9aRHhGSS9pc29CSC9zWm9rClpMWWdxUG4xMHVzVzRCb3Zia0s2aHh0c0NSczBZamliSER2WkdpMkc1RXNCQ0tXbXgrSi9zMTd5SHl6RnN3azAKMkVVM3N4ditGTFJ6SXhFTDAzeStYMFdDZjhkdWl1TzdhVVl3QzFQaVJ4aGxXODBHcmNMbDBSeDlLbjk2SU1iNwpIS1RCaXZYcTc1alJTSHhSc2dRTWlxRGlnWjFJNEEweDM2Q2luMDYwaFNua3JGTmRpcWhXS1pCS3ZYeGYwcEhuCm5QR2h4UUVVeGlWKzJJVmhGKzVMWTBMUHJlVDBYMmROd0ZQWVpHTjlBRGk4NnhWcnBrL3pTdlhCOGRtZDZLS08KNlIvdVlZY041U0dGVG1wRkF5dW00d1hCY0RQa21VdGY1aHVOZXNiTzkrc0tacks1dHY4Tk9BM3E5aXg0bWtGUQpYcm9aU3BCd1h2SGVQeC95YldLYVFoaWpyVVgxRkNTdzdqaWVYaGNvZFFsMG9RMVJvaEhSUFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://rwc7lj.c1.uk1.k8s.ovh.net
  name: jumpy2
contexts:
- context:
    cluster: jumpy2
    user: kubernetes-admin-jumpy2
  name: kubernetes-admin@jumpy2
current-context: kubernetes-admin@jumpy2
kind: Config
preferences: {}
users:
- name: kubernetes-admin-jumpy2
  user:
    token: ""
```
