### ISSUE TITLE
Exporter Socket/Port

### ISSUE THREAD

**Issue by kirkbrauer** [jumpstarter-dev/jumpstarter#64]
## Problem

Currently, exporters can only be used through Leases from the controller or directly using `jmp shell --exporter <exporter>`. However, this requires that the user either configures an entire controller/router or just runs the exporter on-demand from the CLI. Sometimes, it is necessary to have a long-lived exporter running locally that can be accessed using a local socket or port.

This can be useful for running local CI runners such as the GitLab CI Runner where an executor container needs to connect to a local exporter without the Jumpstarter Service. This feature can also be useful for local debugging of a running exporter if the network is down or scripts need to be run locally.

## Feature Proposal

To support local Exporter use cases, we should add a `local` section to the ExporterConfig to enable configuring a Unix socket or TCP port to expose the exporter on. When a client connects to an exporter using a local session, the exporter is taken offline and any active lease is preempted.

```yaml
local:
  enabled: true # Required to enable local access
  socketPath: /var/jumpstarter/exporter.socket # Path to a socket
  tcpPort: 5555 # TCP port for self hosting (optional)
```

### Security

When using a local socket, we can use Linux file permissions to enforce exporter access. For example, a container could mount the socket path as a volume and be given permissions to access it. This would allow for isolated client access separate from the privileged exporter container,

Securing a TCP port is more difficult requiring mTLS or SSH certificate authentication to allow access. This may not be implemented in the initial iteration to reduce complexity.
